# -*- coding: utf-8 -*-
"""expense_tracker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VA9nqd5vWJeFHQmWXfgffj7ojuZHsLjL

#**Expense Tracker**
"""

categories = []
amounts = []

n = int(input("How many expenses do you want to enter? "))

for i in range(n):
    category = input("Enter category: ")
    amount = float(input("Enter amount: "))

    categories.append(category)
    amounts.append(amount)

# Total expense
total = sum(amounts)
print("\nTotal Expense:", total)

# Category-wise expense
category_total = {}

for i in range(len(categories)):
    if categories[i] in category_total:
        category_total[categories[i]] += amounts[i]
    else:
        category_total[categories[i]] = amounts[i]

print("\nCategory-wise spending:")
for category in category_total:
    print(category, ":", category_total[category])